# [Prof. Dalvan Griebler](mailto:dalvan.griebler@pucrs.br)

## Programação Orientada a Dados (POD) - Turma 10 (POD_98H04-06)

**Atualizado**: 21/11/2021

**Descrição**: Trabalho em Grupo: Manipulação, Análise e Visualização Vetorial e Tabular de Dados


**Copyright &copy;**: Este documento está sob a licensa da Criative Commons [BY-NC-ND 4.0](https://creativecommons.org/licenses/by-nc-nd/4.0/legalcode)

## Trabalho realizado por:

## Thiago Macedo e Vitor Pires

# Bibliotecas Autorizadas

Não importe outras bibliotecas além destas, pois não estão autorizadas para o uso.

In [1]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
from PIL import Image

# Manipulação Vetorial

Obs: não será permitido o uso de laços nesta parte do trabalho sobre manipulação vetorial.

## 1. Crie um array 2D `shape(10,10)` com os seguintes valores.

```bash
[[-4 -4  0 -4 -4 -4  0 -4 -4 -4]
 [-4 -4 -4 -4 -4 -4 -4 -4 -4 -4]
 [ 0 -4 -4 -4  0 -4 -4 -4  0 -4]
 [-4 -4 -4 -4 -4 -4 -4 -4 -4 -4]
 [-4 -4  0 -4 -4 -4  0 -4 -4 -4]
 [-4 -4 -4 -4 -4 -4 -4 -4 -4 -4]
 [ 0 -4 -4 -4  0 -4 -4 -4  0 -4]
 [-4 -4 -4 -4 -4 -4 -4 -4 -4 -4]
 [-4 -4  0 -4 -4 -4  0 -4 -4 -4]
 [-4 -4 -4 -4 -4 -4 -4 -4 -4 -4]]
 ```

## 2. Dado os valores `x`, `y1`, `y2` e `y3`, reproduza o seguinte gráfico.
```python
np.random.seed(0)
x = np.arange(10)
y1 = np.array([1.4, 3.2, 2, 4.2, 6.8, 8.7, 9.2, 9, 9.8, 10])
y2 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
y3 = np.array([1, 1.2, 1.3, 1.4, 1.5, 3, 3, 3, 2, 1])
```
**Resultado Esperado:**

![](dados/fig-tg2-ex2.png)

## 3. Dado as funções `sigmoid` e `relu`, apresente em um gráfico o intervalo de `[-6, 6]` com espaçamento de `0.4` entre os elementos para o eixo `_x_`.
```python
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def relu(x):
    return np.maximum(0, x)
```


**Resultado Esperado:**

![](dados/fig-tg2-ex3.png)

## 4. Dado essa [Imagem](dados/dog.png), faça:
- Carregue a imagem em um `np.array`
- Crie uma figura com 3 `Axes` (uma linha e três colunas)
- `Axes` (1, 1): visualize a imagem original
- `Axes` (1, 2): visualize a imagem com um flip horizontal
- `Axes` (1, 3): visualize a imagem com um flip vertical

_Observação: utilize somente idexação e fatiamento_


**Resultado Esperado:**

![](dados/fig-tg2-ex4.png)

# Manipulação Tabular com Dataset FIFA 19

OBS: Todos os gráficos gerados nesta parte precisam ter Título e identificação dos eixos. Permitam também que seja possível visualizar os dados dos eixos.

## 5. Junte as informações dos jogadores que estão distribuidas nos dois arquivos (`fifa19_info_data.csv` e `fifa19_stats_data.csv`). Após isso, corrija apenas os dados que serão usados posteriormente.

Obs: não é permido o uso de laços nesta questão.

_**Sugestão referente aos dados ausentes**: Para o `Dribbling` e `BallControl` preencha os dados ausentes com a média total e para os dados ausentes de `Club` apenas coloque `Sem Clube`._

## 6. Calcule e mostre a média de agilidade e do valor de mercado dos jogadores das equipes de Grêmio e Internacional. 

Obs: não é permido o uso de laços nesta questão.

## 7. Mostre em um gráfico de barras os top 10 clubes baseado na média do controle de bola (`BallControl`) de seus jogadores.

Requisito: colocar o valor com 2 casas decimais após a vírgula no topo de cada barra.


**Resultado Esperado:**

![](dados/fig-tg2-ex7.png)

## 8. Mostre em um gráfico de pizza com porcentagem os 10 países que mais possuem jogadores no conjunto de dados.

Requisito: destaque a menor fatia.

**Resultado Esperado:**

![](dados/fig-tg2-ex8.png)

## 9. Faça uma visualização de `Axes(2,2)` com os seguintes gráficos em ordem:
- histograma com a idade de todos os jogadores
- histograma com a idade dos jogadores do Real Madrid
- histograma com a idade dos jogadores do FC Barcelona
- Histograma com a idade dos jogadores do Paris Saint-Germain

Usar o seguinte intervalo de idades para cada um dos hitogramas.
```
[16, 20, 24, 28, 32, 34, 38, 40, 42]
```

Obs: formate e identifique corretamente cada um dos gráficos.


**Resultado Esperado:**

![](dados/fig-tg2-ex9.png)

## 10. Encontre os 5 clubes com maior e menor potêncial médio dos jogadores. Depois, faça uma figura com dois gráficos `boxplot` do `Dribbling`, sendo um dos 5 maiores potênciais médio e outro dos 5 menores potênciais médio.

**Resultado Esperado:**

![](dados/fig-tg2-ex10.png)